"""empty message

Revision ID: 282bb0fbde69
Revises: 5e671359f59f
Create Date: 2021-01-05 16:36:19.669787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '282bb0fbde69'
down_revision = '5e671359f59f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
