"""empty message

Revision ID: 411485ddc7e1
Revises: 1578512aa2bf
Create Date: 2021-01-05 16:38:36.947846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '411485ddc7e1'
down_revision = '1578512aa2bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
